# Generated by Django 4.1.6 on 2023-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
